# 使用 DeepChem 官方基础镜像
FROM deepchemio/deepchem:latest

# 设置环境变量（可选）
ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

# 安装常用基础工具（如需更精简可省略）
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    bzip2 \
    ca-certificates \
    libglib2.0-0 \
    curl \
    libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*

# 设置工作目录
WORKDIR /workspace
# 有额外安装需求的话
COPY . .
RUN /miniconda/envs/deepchem/bin/pip install --no-cache-dir -r requirements.txt

# 暴露端口
EXPOSE 8000

# 启动API服务
CMD ["/miniconda/envs/deepchem/bin/python", "api.py"] 